stages:
  - build
  - deploy

image: node:latest
cache:
  paths:
    - node_modules/

build:
  stage: build
  tags:
    - pi4
  script:
    - cd src
    - npm ci
    - npm run build
  artifacts:
    paths:
      - src/dist/*
    untracked: false
    expire_in: 1 days

deploy:
  stage: deploy
  tags:
    - hetzner
  script:
    - cd src
    - rm -rf /srv/nginx/wwwroot-fingerfarben/*
    - cp -r dist/* /srv/nginx/wwwroot-fingerfarben/
